name: Hello World Pipeline

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  hello_world_job:
    name: Hello World Job
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"
